/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LP2.view.pages;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import static com.LP2.view.pages.Login.profileType;

/**
 *
 * @author evelyn.ferreira
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form editClientProfile
     */
    public EditProfile() {
        initComponents();

        this.getContentPane().setBackground(Color.decode("14027569"));

        userNameTXT.setFont(new Font("Verdana", 0, 14));
        userNameTXT.setHorizontalAlignment(SwingConstants.CENTER);
        userNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        userNameTXT.setBackground(Color.decode("14027569"));
        userNameTXT.setForeground(Color.white);
        userNameTXT.setCaretColor(Color.white);


        userEmailTXT.setFont(new Font("Verdana", 0, 14));
        userEmailTXT.setHorizontalAlignment(SwingConstants.CENTER);
        userEmailTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        userEmailTXT.setBackground(Color.decode("14027569"));
        userEmailTXT.setForeground(Color.white);
        userEmailTXT.setCaretColor(Color.white);

        userCpfTXT.setFont(new Font("Verdana", 0, 14));
        userCpfTXT.setHorizontalAlignment(SwingConstants.CENTER);
        userCpfTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        userCpfTXT.setBackground(Color.decode("14027569"));
        userCpfTXT.setForeground(Color.white);
        userCpfTXT.setCaretColor(Color.white);

        userPhoneTXT.setFont(new Font("Verdana", 0, 14));
        userPhoneTXT.setHorizontalAlignment(SwingConstants.CENTER);
        userPhoneTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        userPhoneTXT.setBackground(Color.decode("14027569"));
        userPhoneTXT.setForeground(Color.white);
        userPhoneTXT.setCaretColor(Color.white);

        fillUserFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBackBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        userEmailTXT = new javax.swing.JTextField();
        userCpfTXT = new javax.swing.JFormattedTextField();
        userNameTXT = new javax.swing.JTextField();
        userPhoneTXT = new javax.swing.JFormattedTextField();
        saveBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar cadastro La Cocina Bistrô");
        setResizable(false);

        editBackBTN.setBackground(new java.awt.Color(38, 70, 27));
        editBackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        editBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBackBTNMouseClicked(evt);
            }
        });

        jPanel1.setOpaque(false);

        userEmailTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        userEmailTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        userEmailTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userEmailTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userEmailTXTFocusLost(evt);
            }
        });

        try {
            userCpfTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        userCpfTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        userCpfTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userCpfTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userCpfTXTFocusLost(evt);
            }
        });

        userNameTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        userNameTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        userNameTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTXTFocusLost(evt);
            }
        });

        try {
            userPhoneTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        userPhoneTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        userPhoneTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPhoneTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPhoneTXTFocusLost(evt);
            }
        });

        saveBTN.setBackground(new java.awt.Color(38, 70, 27));
        saveBTN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("Salvar");
        saveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userEmailTXT)
            .addComponent(userNameTXT)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(userCpfTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(userPhoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(userEmailTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCpfTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPhoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        logoutBTN.setBackground(new java.awt.Color(38, 70, 27));
        logoutBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout24.png"))); // NOI18N
        logoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBTN)
                            .addComponent(editBackBTN))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBackBTNMouseClicked
       if (profileType == 1){
            ManagerAccount managerAcountScreen = new ManagerAccount();
            managerAcountScreen.setVisible(true);
        }else if (profileType == 2){
            KitchenAccount kitchenAcountScreen = new KitchenAccount();
            kitchenAcountScreen.setVisible(true);
        }else{
            UsersAccount usersAcountScreen = new UsersAccount();
            usersAcountScreen.setVisible(true);
        }
        this.dispose();

    }//GEN-LAST:event_editBackBTNMouseClicked

    private void saveBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBTNMouseClicked
        userNameTXT.getText();
        userEmailTXT.getText();
        userCpfTXT.getText();
        userPhoneTXT.getText();
//        mandar as coisaaaas pro bd
//Se rolou tuto certo
        Success successDialog = new Success(this , true);
        successDialog.setVisible(true);
// SE não
        Error errorDialog = new Error(this , true);
        errorDialog.setVisible(true);
    }//GEN-LAST:event_saveBTNMouseClicked

    private void logoutBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBTNMouseClicked
         this.dispose();
        Login loginScreen = new Login();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_logoutBTNMouseClicked

    private void userNameTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTXTFocusGained
        userNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_userNameTXTFocusGained

    private void userNameTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTXTFocusLost
        userNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_userNameTXTFocusLost

    private void userEmailTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailTXTFocusGained
        userEmailTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_userEmailTXTFocusGained

    private void userEmailTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailTXTFocusLost
        userEmailTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_userEmailTXTFocusLost

    private void userCpfTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userCpfTXTFocusGained
        userCpfTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_userCpfTXTFocusGained

    private void userCpfTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userCpfTXTFocusLost
        userCpfTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_userCpfTXTFocusLost

    private void userPhoneTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPhoneTXTFocusGained
        userPhoneTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_userPhoneTXTFocusGained

    private void userPhoneTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPhoneTXTFocusLost
        userPhoneTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_userPhoneTXTFocusLost

    private void fillUserFields() {

//            pegar obj do banco, buscar pelo email do Login
        userNameTXT.setText("string nome");
        userEmailTXT.setText("string nome");
        userCpfTXT.setText("86344792507");
        userPhoneTXT.setText("(21)22222-2222");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBackBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JFormattedTextField userCpfTXT;
    private javax.swing.JTextField userEmailTXT;
    private javax.swing.JTextField userNameTXT;
    private javax.swing.JFormattedTextField userPhoneTXT;
    // End of variables declaration//GEN-END:variables
}
