/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LP2.view.pages;

import java.awt.Color;
import java.awt.Font;
import java.awt.im.InputContext;
import static java.lang.Integer.parseInt;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import static com.LP2.view.pages.Login.profileType;

/**
 *
 * @author evelyn.ferreira
 */
public class ItemDetailed extends javax.swing.JFrame {

    /**
     * Creates new form ItemDeatailed
     */
    public ItemDetailed() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("14027569"));
        quantityTXT.setDocument(new JustNumbers());
        quantityTXT.setText("1");
        quantityTXT.setFont(new Font("Verdana",0, 14));
        quantityTXT.setHorizontalAlignment(SwingConstants.CENTER);
        quantityTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        quantityTXT.setBackground(Color.decode("14027569"));
        quantityTXT.setForeground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameitemTXT = new javax.swing.JLabel();
        imageItemIMG = new javax.swing.JLabel();
        priceItemTXT = new javax.swing.JLabel();
        descriptionItemTXT1 = new javax.swing.JLabel();
        backDetailedItemBTN = new javax.swing.JButton();
        addCartBTN = new javax.swing.JButton();
        feedBackBTN = new javax.swing.JButton();
        plusBTN = new javax.swing.JLabel();
        minusBTN = new javax.swing.JLabel();
        quantityTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalhes do item");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        NameitemTXT.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameitemTXT.setForeground(new java.awt.Color(255, 255, 255));
        NameitemTXT.setText("nome");

        imageItemIMG.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imageItemIMG.setForeground(new java.awt.Color(255, 255, 255));
        imageItemIMG.setText("imagem");

        priceItemTXT.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        priceItemTXT.setForeground(new java.awt.Color(255, 255, 255));
        priceItemTXT.setText("price");

        descriptionItemTXT1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        descriptionItemTXT1.setForeground(new java.awt.Color(255, 255, 255));
        descriptionItemTXT1.setText("desc");

        backDetailedItemBTN.setBackground(new java.awt.Color(38, 70, 27));
        backDetailedItemBTN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        backDetailedItemBTN.setForeground(new java.awt.Color(255, 255, 255));
        backDetailedItemBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        backDetailedItemBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backDetailedItemBTNMouseClicked(evt);
            }
        });

        addCartBTN.setBackground(new java.awt.Color(38, 70, 27));
        addCartBTN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addCartBTN.setForeground(new java.awt.Color(255, 255, 255));
        addCartBTN.setText("Adcionar");
        addCartBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCartBTNMouseClicked(evt);
            }
        });

        feedBackBTN.setBackground(new java.awt.Color(38, 70, 27));
        feedBackBTN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        feedBackBTN.setForeground(new java.awt.Color(255, 255, 255));
        feedBackBTN.setText("Feedback");

        plusBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus20.png"))); // NOI18N
        plusBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusBTNMouseExited(evt);
            }
        });

        minusBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minus20.png"))); // NOI18N
        minusBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minusBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minusBTNMouseExited(evt);
            }
        });

        quantityTXT.setEditable(false);
        quantityTXT.setText("1");
        quantityTXT.setSelectionColor(new java.awt.Color(214, 11, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(imageItemIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backDetailedItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NameitemTXT)
                                        .addGap(170, 170, 170)
                                        .addComponent(priceItemTXT)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(36, 36, 36)
                                        .addComponent(feedBackBTN))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(minusBTN)
                                .addGap(18, 18, 18)
                                .addComponent(quantityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(plusBTN)
                                .addGap(18, 18, 18)
                                .addComponent(addCartBTN)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(descriptionItemTXT1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backDetailedItemBTN)
                    .addComponent(feedBackBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameitemTXT)
                    .addComponent(priceItemTXT))
                .addGap(18, 18, 18)
                .addComponent(imageItemIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriptionItemTXT1)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCartBTN)
                        .addComponent(minusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quantityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backDetailedItemBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backDetailedItemBTNMouseClicked
        this.dispose();
        Menu menuScreen = new Menu();
        menuScreen.setVisible(true);
    }//GEN-LAST:event_backDetailedItemBTNMouseClicked

    private void addCartBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCartBTNMouseClicked

        if (profileType > 3 || profileType < 1) {
            this.dispose();
            Login loginScreen = new Login();
            loginScreen.setVisible(true);
        } else {
            // Adcionar ao carrinho
            this.dispose();
            Menu menuScreen = new Menu();
            menuScreen.setVisible(true);
        }
    }//GEN-LAST:event_addCartBTNMouseClicked

    private void plusBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusBTNMouseEntered
        plusBTN.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\hoverPlus20.png"));
    }//GEN-LAST:event_plusBTNMouseEntered

    private void plusBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusBTNMouseExited
        plusBTN.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\plus20.png"));
    }//GEN-LAST:event_plusBTNMouseExited

    private void minusBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusBTNMouseEntered
        minusBTN.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\hoverMinus20.png"));
    }//GEN-LAST:event_minusBTNMouseEntered

    private void minusBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusBTNMouseExited
        minusBTN.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\minus20.png"));
    }//GEN-LAST:event_minusBTNMouseExited

    private void minusBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusBTNMouseClicked
        String quantity = quantityTXT.getText();
        int strInt = parseInt(quantity);
        if (strInt > 1){
            strInt = strInt - 1 ;
            quantity = Integer.toString(strInt);
            quantityTXT.setText(quantity);
        }
    }//GEN-LAST:event_minusBTNMouseClicked

    private void plusBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusBTNMouseClicked
        String quantity = quantityTXT.getText();
        int strInt = parseInt(quantity);
        if (strInt < 40){
            strInt = strInt + 1 ;
            quantity = Integer.toString(strInt);
            quantityTXT.setText(quantity);
        }
    }//GEN-LAST:event_plusBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){

            @Override
            public void run() {
                new ItemDetailed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameitemTXT;
    private javax.swing.JButton addCartBTN;
    private javax.swing.JButton backDetailedItemBTN;
    private javax.swing.JLabel descriptionItemTXT1;
    private javax.swing.JButton feedBackBTN;
    private javax.swing.JLabel imageItemIMG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minusBTN;
    private javax.swing.JLabel plusBTN;
    private javax.swing.JLabel priceItemTXT;
    private javax.swing.JTextField quantityTXT;
    // End of variables declaration//GEN-END:variables
}
