/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LP2.view.pages;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import static com.LP2.view.pages.CustomizeMenuBar.CustomizeMenuBar;

/**
 *
 * @author Blueevee
 */
public class KitchenAccount extends javax.swing.JFrame {

    /**
     * Creates new form kitchenAcount
     */
    public KitchenAccount() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("14027569"));
        CustomizeMenuBar(kitchenMENU, Color.decode("14027569"), Color.white );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitchenBackBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitchenTBL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        kitchenMENU = new javax.swing.JMenuBar();
        editProfileMENU = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cozinha La Cocina Bistrô");
        setResizable(false);

        kitchenBackBTN.setBackground(new java.awt.Color(38, 70, 27));
        kitchenBackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        kitchenBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitchenBackBTNMouseClicked(evt);
            }
        });

        kitchenTBL.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        kitchenTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MESA", "QUANTIDADE", "PEDIDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kitchenTBL);
        if (kitchenTBL.getColumnModel().getColumnCount() > 0) {
            kitchenTBL.getColumnModel().getColumn(0).setPreferredWidth(2);
            kitchenTBL.getColumnModel().getColumn(1).setPreferredWidth(2);
            kitchenTBL.getColumnModel().getColumn(2).setPreferredWidth(96);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        editProfileMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profileEdit16.png"))); // NOI18N
        editProfileMENU.setText("Perfil");
        editProfileMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMENUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMENUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMENUMouseExited(evt);
            }
        });
        kitchenMENU.add(editProfileMENU);
        kitchenMENU.add(jMenu2);

        setJMenuBar(kitchenMENU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kitchenBackBTN)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(kitchenBackBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kitchenBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitchenBackBTNMouseClicked
        this.dispose();
        Login loginScreen = new Login();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_kitchenBackBTNMouseClicked

    private void editProfileMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMENUMouseEntered
        editProfileMENU.setForeground(Color.decode("6554655"));
        editProfileMENU.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\hoverProfileEdit.png"));
    }//GEN-LAST:event_editProfileMENUMouseEntered

    private void editProfileMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMENUMouseExited
        editProfileMENU.setForeground(Color.white);
        editProfileMENU.setIcon(new ImageIcon("C:\\Users\\evelyn.ferreira\\Desktop\\laCocina-master\\src\\assets\\profileEdit16.png"));
    }//GEN-LAST:event_editProfileMENUMouseExited

    private void editProfileMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMENUMouseClicked
        this.dispose();
        EditProfile editProfileScreen = new EditProfile();
        editProfileScreen.setVisible(true);
    }//GEN-LAST:event_editProfileMENUMouseClicked
    private void loadTable(){

        DefaultTableModel model = (DefaultTableModel) kitchenTBL.getModel();
        model.setNumRows(0);

        kitchenTBL.getColumnModel().getColumn(0).setPreferredWidth(2);
        kitchenTBL.getColumnModel().getColumn(1).setPreferredWidth(2);
        kitchenTBL.getColumnModel().getColumn(2).setPreferredWidth(96);

//        pegar do bd e preencher as linhas
        model.addRow(new Object[]{


        });


    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitchenAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitchenAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitchenAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitchenAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){

            @Override
            public void run() {
                new KitchenAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editProfileMENU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kitchenBackBTN;
    private javax.swing.JMenuBar kitchenMENU;
    private javax.swing.JTable kitchenTBL;
    // End of variables declaration//GEN-END:variables

    private Object one(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
