/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LP2.view.pages;

import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author evelyn.ferreira
 */
public class Menu extends javax.swing.JFrame {
    DefaultComboBoxModel  modelCBOX = new DefaultComboBoxModel();
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("14027569"));
        foodTypeCBOX.setModel(modelCBOX);
        addItem();
        foodTypeCBOX.setBackground(Color.decode("2508315"));
        foodTypeCBOX.setForeground(Color.white);

        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        menuBackBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTBL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cashbackTXT = new javax.swing.JLabel();
        valueCashbackTXT = new javax.swing.JLabel();
        foodTypeCBOX = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu La Cocina Bistrô");

        menuBackBTN.setBackground(new java.awt.Color(38, 70, 27));
        menuBackBTN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        menuBackBTN.setIcon(new ImageIcon("assets/back16.png")); // NOI18N
        menuBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackBTNMouseClicked(evt);
            }
        });

        jPanel1.setOpaque(false);

        menuTBL.setAutoCreateRowSorter(true);
        menuTBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        menuTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10", "batata", "2,30"},
                {"12", "peixe", "1"},
                {"11", "euuu", "6,80"},
                {"20", "feijã0", "20"},
                {"27", "arroz", null}
            },
            new String [] {
                "Código", "Prato", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTBL.getTableHeader().setReorderingAllowed(false);
        menuTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTBL);
        if (menuTBL.getColumnModel().getColumnCount() > 0) {
            menuTBL.getColumnModel().getColumn(0).setPreferredWidth(2);
            menuTBL.getColumnModel().getColumn(1).setPreferredWidth(96);
            menuTBL.getColumnModel().getColumn(2).setPreferredWidth(2);
        }

        jLabel2.setIcon(new ImageIcon("assets/logo.png")); // NOI18N

        cashbackTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cashbackTXT.setForeground(new java.awt.Color(255, 255, 255));
        cashbackTXT.setText("Cashback:");

        valueCashbackTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        valueCashbackTXT.setForeground(new java.awt.Color(255, 255, 255));
        valueCashbackTXT.setText("value");

        foodTypeCBOX.setBackground(new java.awt.Color(38, 70, 27));
        foodTypeCBOX.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        foodTypeCBOX.setForeground(new java.awt.Color(255, 255, 255));
        foodTypeCBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        foodTypeCBOX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTypeCBOXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cashbackTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueCashbackTXT))
                    .addComponent(foodTypeCBOX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashbackTXT)
                            .addComponent(valueCashbackTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(foodTypeCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBackBTN)
                .addContainerGap(534, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackBTNMouseClicked
        this.dispose();
        Login loginScreen = new Login();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_menuBackBTNMouseClicked

    private void menuTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTBLMouseClicked
//        Menu item = new Menu();
//        MenuDAO dao = new MenuDao();

        int index = menuTBL.getSelectedRow();
        if(index > -1){
            this.dispose();
            ItemDetailed itemScreen = new ItemDetailed();
            itemScreen.setVisible(true);

//            item = dao.Listar().get(index);
        }

    }//GEN-LAST:event_menuTBLMouseClicked

    private void foodTypeCBOXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTypeCBOXMouseClicked
        String type = (String) foodTypeCBOX.getSelectedItem();

            ///Trazer todos que tenham Type
            loadTable();
    }//GEN-LAST:event_foodTypeCBOXMouseClicked
     private void loadTable(){

        DefaultTableModel model = (DefaultTableModel) menuTBL.getModel();
        model.setNumRows(0);

        menuTBL.getColumnModel().getColumn(0).setPreferredWidth(2);
        menuTBL.getColumnModel().getColumn(1).setPreferredWidth(96);
        menuTBL.getColumnModel().getColumn(2).setPreferredWidth(2);

//        MenuDao dao = new MenuDao();
//        for(Menu item: dao.List()){
//            model.addRow(new Object[]{
//                item.getId(),
//                item.getName,
//                item.getPrice
//            });
//        }

    }
    private void addItem(){
        String[] foodType = {
            "Todos",
            "Veganos",
            "Bebidas",
            "Picantes",
            "Do chef"};
        for(String type: foodType){
            modelCBOX.addElement(type);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){

          @Override
          public void run() {
            new Menu().setVisible(true);
          }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashbackTXT;
    private javax.swing.JComboBox<String> foodTypeCBOX;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menuBackBTN;
    private javax.swing.JTable menuTBL;
    private javax.swing.JLabel valueCashbackTXT;
    // End of variables declaration//GEN-END:variables
}