/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LP2.view.pages;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;

/**
 *
 * @author evelyn.ferreira
 */
public class RegisterProducts extends javax.swing.JFrame {

    /**
     * Creates new form registerProducts
     */
    public RegisterProducts() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("14027569"));
        productDrinkRBTN.setSelected(true);

        PlaceHolder placeHolderName = new PlaceHolder(productNameTXT, Color.white, Color.white, "Qual o nome do produto?", false, "Verdana", 14);
        PlaceHolder placeHolderPrice = new PlaceHolder(productPriceTXT, Color.white, Color.white, "Preço", false, "Verdana", 14);
        PlaceHolder placeHolderProvider = new PlaceHolder(drinkProviderTXT, Color.white, Color.white, "Fornecedor", false, "Verdana", 14);
        PlaceHolder placeHolderDescription = new PlaceHolder(foodDescriptionTXT, Color.white, Color.white, "Descrição do item", false, "Verdana", 14);

        productNameTXT.setFont(new Font("Verdana", 0, 14));
        productNameTXT.setHorizontalAlignment(SwingConstants.CENTER);
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        productNameTXT.setBackground(Color.decode("14027569"));
        productNameTXT.setForeground(Color.white);
        productNameTXT.setCaretColor(Color.white);

        productPriceTXT.setFont(new Font("Verdana", 0, 14));
        productPriceTXT.setHorizontalAlignment(SwingConstants.CENTER);
        productPriceTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        productPriceTXT.setBackground(Color.decode("14027569"));
        productPriceTXT.setForeground(Color.white);
        productPriceTXT.setCaretColor(Color.white);

        drinkProviderTXT.setFont(new Font("Verdana", 0, 14));
        drinkProviderTXT.setHorizontalAlignment(SwingConstants.CENTER);
        drinkProviderTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        drinkProviderTXT.setBackground(Color.decode("14027569"));
        drinkProviderTXT.setForeground(Color.white);
        drinkProviderTXT.setCaretColor(Color.white);

        foodDescriptionTXT.setFont(new Font("Verdana", 0, 14));
        foodDescriptionTXT.setHorizontalAlignment(SwingConstants.CENTER);
        foodDescriptionTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
        foodDescriptionTXT.setBackground(Color.decode("14027569"));
        foodDescriptionTXT.setForeground(Color.white);
        foodDescriptionTXT.setCaretColor(Color.white);

        emptyDataLBL.setVisible(false);
        emptyData2LBL.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choicefoodGRP = new javax.swing.ButtonGroup();
        productsBackBTN = new javax.swing.JButton();
        registerProductsPNL = new javax.swing.JPanel();
        Cadastrar = new javax.swing.JButton();
        productNameTXT = new javax.swing.JTextField();
        productFoodRBTN = new javax.swing.JRadioButton();
        productDrinkRBTN = new javax.swing.JRadioButton();
        drinkProviderTXT = new javax.swing.JTextField();
        productPriceTXT = new javax.swing.JTextField();
        emptyDataLBL = new javax.swing.JLabel();
        emptyData2LBL = new javax.swing.JLabel();
        foodDescriptionTXT = new javax.swing.JTextField();
        emptyData2LBL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        productsBackBTN.setBackground(new java.awt.Color(38, 70, 27));
        productsBackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        productsBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsBackBTNMouseClicked(evt);
            }
        });

        registerProductsPNL.setOpaque(false);

        Cadastrar.setBackground(new java.awt.Color(38, 70, 27));
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("Cadastrar");
        Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMouseClicked(evt);
            }
        });

        productNameTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        productNameTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        productNameTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productNameTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                productNameTXTFocusLost(evt);
            }
        });

        choicefoodGRP.add(productFoodRBTN);
        productFoodRBTN.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        productFoodRBTN.setForeground(new java.awt.Color(255, 255, 255));
        productFoodRBTN.setText("Comida");
        productFoodRBTN.setOpaque(false);
        productFoodRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productFoodRBTNMouseClicked(evt);
            }
        });

        choicefoodGRP.add(productDrinkRBTN);
        productDrinkRBTN.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        productDrinkRBTN.setForeground(new java.awt.Color(255, 255, 255));
        productDrinkRBTN.setText("Bebida");
        productDrinkRBTN.setOpaque(false);
        productDrinkRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productDrinkRBTNMouseClicked(evt);
            }
        });

        drinkProviderTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        drinkProviderTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        drinkProviderTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                drinkProviderTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                drinkProviderTXTFocusLost(evt);
            }
        });

        productPriceTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        productPriceTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        productPriceTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productPriceTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                productPriceTXTFocusLost(evt);
            }
        });

        emptyDataLBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emptyDataLBL.setForeground(new java.awt.Color(255, 255, 255));
        emptyDataLBL.setText("* Todos os campos devem");

        emptyData2LBL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emptyData2LBL.setForeground(new java.awt.Color(255, 255, 255));
        emptyData2LBL.setText("ser preenchidos");

        foodDescriptionTXT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        foodDescriptionTXT.setSelectionColor(new java.awt.Color(214, 11, 49));
        foodDescriptionTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                foodDescriptionTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                foodDescriptionTXTFocusLost(evt);
            }
        });

        javax.swing.GroupLayout registerProductsPNLLayout = new javax.swing.GroupLayout(registerProductsPNL);
        registerProductsPNL.setLayout(registerProductsPNLLayout);
        registerProductsPNLLayout.setHorizontalGroup(
            registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerProductsPNLLayout.createSequentialGroup()
                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerProductsPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productFoodRBTN)
                        .addGap(86, 86, 86)
                        .addComponent(productDrinkRBTN))
                    .addComponent(drinkProviderTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(productNameTXT)
                    .addComponent(foodDescriptionTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerProductsPNLLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerProductsPNLLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(productPriceTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerProductsPNLLayout.createSequentialGroup()
                                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerProductsPNLLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(emptyData2LBL))
                                    .addComponent(emptyDataLBL))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerProductsPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        registerProductsPNLLayout.setVerticalGroup(
            registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerProductsPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPriceTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productFoodRBTN)
                    .addComponent(productDrinkRBTN))
                .addGap(18, 18, 18)
                .addGroup(registerProductsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerProductsPNLLayout.createSequentialGroup()
                        .addComponent(emptyDataLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emptyData2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerProductsPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(drinkProviderTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(foodDescriptionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );

        emptyData2LBL1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emptyData2LBL1.setForeground(new java.awt.Color(255, 255, 255));
        emptyData2LBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsBackBTN)
                .addGap(75, 75, 75)
                .addComponent(emptyData2LBL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerProductsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productsBackBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(emptyData2LBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerProductsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productsBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsBackBTNMouseClicked
        this.dispose();
        ManagerAccount managerScreen = new ManagerAccount();
        managerScreen.setVisible(true);
    }//GEN-LAST:event_productsBackBTNMouseClicked

    private void productFoodRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productFoodRBTNMouseClicked
       foodDescriptionTXT.setVisible(true);
       drinkProviderTXT.setVisible(false);
    }//GEN-LAST:event_productFoodRBTNMouseClicked

    private void productDrinkRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDrinkRBTNMouseClicked
        drinkProviderTXT.setVisible(true);
        foodDescriptionTXT.setVisible(false);
    }//GEN-LAST:event_productDrinkRBTNMouseClicked

    private void CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseClicked
        if((drinkProviderTXT.getText().trim().isEmpty() &&
           foodDescriptionTXT.getText().trim().isEmpty()) ||
           productNameTXT.getText().trim().isEmpty() ||
           productPriceTXT.getText().trim().isEmpty()){

            emptyDataLBL.setVisible(true);
            emptyData2LBL.setVisible(true);
        }

        //Se rolou tuto certo
        Success successDialog = new Success(this , true);
        successDialog.setVisible(true);
// SE não
        Error errorDialog = new Error(this , true);
        errorDialog.setVisible(true);

    }//GEN-LAST:event_CadastrarMouseClicked

    private void productNameTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameTXTFocusGained
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_productNameTXTFocusGained

    private void productNameTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameTXTFocusLost
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_productNameTXTFocusLost

    private void productPriceTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productPriceTXTFocusGained
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_productPriceTXTFocusGained

    private void productPriceTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productPriceTXTFocusLost
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_productPriceTXTFocusLost

    private void drinkProviderTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_drinkProviderTXTFocusGained
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_drinkProviderTXTFocusGained

    private void drinkProviderTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_drinkProviderTXTFocusLost
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_drinkProviderTXTFocusLost

    private void foodDescriptionTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foodDescriptionTXTFocusGained
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("6554655")));
    }//GEN-LAST:event_foodDescriptionTXTFocusGained

    private void foodDescriptionTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foodDescriptionTXTFocusLost
        productNameTXT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));
    }//GEN-LAST:event_foodDescriptionTXTFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){

            @Override
            public void run() {
                new RegisterProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.ButtonGroup choicefoodGRP;
    private javax.swing.JTextField drinkProviderTXT;
    private javax.swing.JLabel emptyData2LBL;
    private javax.swing.JLabel emptyData2LBL1;
    private javax.swing.JLabel emptyDataLBL;
    private javax.swing.JTextField foodDescriptionTXT;
    private javax.swing.JRadioButton productDrinkRBTN;
    private javax.swing.JRadioButton productFoodRBTN;
    private javax.swing.JTextField productNameTXT;
    private javax.swing.JTextField productPriceTXT;
    private javax.swing.JButton productsBackBTN;
    private javax.swing.JPanel registerProductsPNL;
    // End of variables declaration//GEN-END:variables
}
