/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import static java.awt.Color.BLACK;
import static java.awt.Color.BLUE;
import static java.awt.Color.GRAY;
import static java.awt.Color.green;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javafx.scene.paint.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author JACK
 */
public class ReviewsClient extends javax.swing.JFrame {

    /**
     * Creates new form ReviewsClient
     */
    
    
    public static String food;
    
    public ReviewsClient() {
        initComponents();
        this.setTitle("Meus feedbacks");
        
        
        this.getContentPane().setBackground(java.awt.Color.decode("14027569"));
        feedbackClient.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        feedbackClient.setForeground(BLUE);
        feedbackClient.setRowHeight(25);
        carregarTabela();
        
        
        
        
        
        // Detectar clique do mouse em linha especifica
            feedbackClient.addMouseListener(new MouseAdapter(){
       public void mouseClicked(MouseEvent me){
           int column = feedbackClient.columnAtPoint(me.getPoint());    
           
           
           if (column == 2){
               ReadReview read = new ReadReview();
               read.setVisible(true);
           }
               
           
           
           if(me.getClickCount() > 1){
               
               int row = feedbackClient.rowAtPoint(me.getPoint());
               
               //JOptionPane.showMessageDialog(null, "Teste " + column);

               String food = (String) feedbackClient.getValueAt(feedbackClient.getSelectedRow(), 0);
               //JOptionPane.showMessageDialog(null, "Teste "+ food);
               
               //System.out.println("You clicked at row " + row);
               //System.out.println ("You clicked at food " + food);
           }

       }
        
    });
        
    }
    


  
    
    
    
    
    public void carregarTabela(){
        
        
        
        DefaultTableModel model = (DefaultTableModel) feedbackClient.getModel();
        model.setNumRows(0);
        
            PessoaRandom p = new PessoaRandom("Bolo");
            PessoaRandom p2 = new PessoaRandom("Doce");
            PratoRandom pr = new PratoRandom("16/03/2020");
        
        feedbackClient.getColumnModel().getColumn(0).setPreferredWidth(20);
        feedbackClient.getColumnModel().getColumn(1).setPreferredWidth(10);
        
       // feedbackClient.getColumnModel().getColumn(2).setPreferredWidth(10);
        
        
        try{

            model.addRow(new Object[]{
               p.nome,
               pr.comida,
               "Ver mais"
            });
            
            model.addRow(new Object[]{
               p2.nome,
               pr.comida,
               "Ver mais"
            });
            
        }catch(Exception erroSQL){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");

        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackClient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        feedbackClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Data ", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(feedbackClient);
        if (feedbackClient.getColumnModel().getColumnCount() > 0) {
            feedbackClient.getColumnModel().getColumn(0).setPreferredWidth(42);
            feedbackClient.getColumnModel().getColumn(1).setPreferredWidth(23);
            feedbackClient.getColumnModel().getColumn(2).setPreferredWidth(-15);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JACK\\Desktop\\testeJava\\laCocina-master\\src\\assets\\logo.png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JACK\\Desktop\\testeJava\\TelasIndependentes\\build\\classes\\assets\\back16.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewsClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable feedbackClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
