/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import jtextfieldround.BorderLineRound;

/**
 *
 * @author evelyn.ferreira
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
         
        PlaceHolder placeHolderName = new PlaceHolder(registerNameTXT, "Aqui vai seu nome:D");
        PlaceHolder placeHolderPassword = new PlaceHolder(registerPasswordTXT, "Sua senha shh..");
        PlaceHolder placeHolderConfirmPassword = new PlaceHolder(registerConfirmPasswordTXT, "Sua senha shh..");
        PlaceHolder placeHolderEmail = new PlaceHolder(registerEmailTXT, "E aqui seu melhor endereço de Email :P");
        
        registerNameTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerNameTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerNameTXT.setHorizontalAlignment(SwingConstants.CENTER);
    
        registerPhoneTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerPhoneTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerPhoneTXT.setHorizontalAlignment(SwingConstants.CENTER);
        
        registerEmailTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerEmailTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerEmailTXT.setHorizontalAlignment(SwingConstants.CENTER);
        
        registerCodeTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerCodeTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerCodeTXT.setHorizontalAlignment(SwingConstants.CENTER);
    
        registerConfirmPasswordTXT.setEchoChar('°');
        registerConfirmPasswordTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerConfirmPasswordTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerConfirmPasswordTXT.setHorizontalAlignment(SwingConstants.CENTER);
        
        registerPasswordTXT.setEchoChar('°');
        registerPasswordTXT.setBorder(new BorderLineRound(Color.GRAY, true)); 
        registerPasswordTXT.setFont(new Font("Helvetica", 0, 12)); 
        registerPasswordTXT.setHorizontalAlignment(SwingConstants.CENTER);
        
        registerBTN.setBorder(new BorderLineRound(Color.decode("11326409"), true));
        registerBTN.setHorizontalAlignment(SwingConstants.CENTER);
        
        wrongPasswordLBL.setVisible(false);
        emptyDataLBL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerBackBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        registerNameTXT = new javax.swing.JTextField();
        registerPhoneTXT = new javax.swing.JFormattedTextField();
        registerCodeTXT = new javax.swing.JFormattedTextField();
        registerPasswordTXT = new javax.swing.JPasswordField();
        registerConfirmPasswordTXT = new javax.swing.JPasswordField();
        registerBTN = new javax.swing.JButton();
        registerEmailTXT = new javax.swing.JTextField();
        wrongPasswordLBL = new javax.swing.JLabel();
        emptyDataLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        registerBackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        registerBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBackBTNMouseClicked(evt);
            }
        });

        try {
            registerPhoneTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        registerPhoneTXT.setToolTipText("Seu melhor telefone");
        registerPhoneTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPhoneTXTActionPerformed(evt);
            }
        });

        try {
            registerCodeTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        registerCodeTXT.setToolTipText("Seu CPF vai aqui");

        registerPasswordTXT.setToolTipText("Sua senha");

        registerConfirmPasswordTXT.setToolTipText("Confirmar senha");
        registerConfirmPasswordTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerConfirmPasswordTXTActionPerformed(evt);
            }
        });

        registerBTN.setBackground(new java.awt.Color(172, 211, 201));
        registerBTN.setText("Cadastrar");
        registerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBTNMouseClicked(evt);
            }
        });
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });

        wrongPasswordLBL.setForeground(new java.awt.Color(255, 51, 51));
        wrongPasswordLBL.setText("*As senhas não coincidem");

        emptyDataLBL.setForeground(new java.awt.Color(255, 51, 51));
        emptyDataLBL.setText("*Você deve preencher todos os campos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wrongPasswordLBL)
                                    .addComponent(emptyDataLBL)))
                            .addComponent(registerCodeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(registerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(registerPhoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(registerEmailTXT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerPasswordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerConfirmPasswordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registerNameTXT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(registerNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerPasswordTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(registerConfirmPasswordTXT))
                .addGap(18, 18, 18)
                .addComponent(registerEmailTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPhoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerCodeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(wrongPasswordLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emptyDataLBL)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registerBackBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerBackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBackBTNMouseClicked
        this.dispose();
        login loginScreen = new login();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_registerBackBTNMouseClicked

    private void registerPhoneTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPhoneTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPhoneTXTActionPerformed

    private void registerConfirmPasswordTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerConfirmPasswordTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerConfirmPasswordTXTActionPerformed

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBTNActionPerformed

    private void registerBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBTNMouseClicked
        if(!new String(registerPasswordTXT.getPassword()).equals(new String(registerConfirmPasswordTXT.getPassword()))){
            wrongPasswordLBL.setVisible(true);
        }
        if(registerNameTXT.getText().trim().isEmpty() ||
           registerEmailTXT.getText().trim().isEmpty() || 
           registerCodeTXT.getText().trim().isEmpty() || 
           registerPhoneTXT.getText().trim().isEmpty() || 
           new String(registerPasswordTXT.getPassword()).trim().isEmpty() || 
           new String(registerConfirmPasswordTXT.getPassword()).trim().isEmpty()){
                emptyDataLBL.setVisible(true);
        }
    }//GEN-LAST:event_registerBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emptyDataLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerBTN;
    private javax.swing.JButton registerBackBTN;
    private javax.swing.JFormattedTextField registerCodeTXT;
    private javax.swing.JPasswordField registerConfirmPasswordTXT;
    private javax.swing.JTextField registerEmailTXT;
    private javax.swing.JTextField registerNameTXT;
    private javax.swing.JPasswordField registerPasswordTXT;
    private javax.swing.JFormattedTextField registerPhoneTXT;
    private javax.swing.JLabel wrongPasswordLBL;
    // End of variables declaration//GEN-END:variables
}
