/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author evelyn.ferreira
 */
public class usersAcount extends javax.swing.JFrame {

    /**
     * Creates new form usersAcount
     */
    public usersAcount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBackBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userMENU = new javax.swing.JMenuBar();
        cartMENU = new javax.swing.JMenu();
        editProfileMENU = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userBackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back16.png"))); // NOI18N
        userBackBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBackBTNMouseClicked(evt);
            }
        });

        jLabel1.setText("AQUI VAI O CARDÁPIO");

        cartMENU.setText("Carrinho");
        cartMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMENUMouseClicked(evt);
            }
        });
        userMENU.add(cartMENU);

        editProfileMENU.setText("Editar Perfil");
        editProfileMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMENUMouseClicked(evt);
            }
        });
        userMENU.add(editProfileMENU);

        setJMenuBar(userMENU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userBackBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userBackBTN)
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userBackBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBackBTNMouseClicked
        this.dispose();
        login loginScreen = new login();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_userBackBTNMouseClicked

    private void editProfileMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMENUMouseClicked
        this.dispose();
        editClientProfile editClientProfileScreen = new editClientProfile();
        editClientProfileScreen.setVisible(true);
    }//GEN-LAST:event_editProfileMENUMouseClicked

    private void cartMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMENUMouseClicked
        this.dispose();
        cart cartScreen = new cart();
        cartScreen.setVisible(true);
    }//GEN-LAST:event_cartMENUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersAcount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cartMENU;
    private javax.swing.JMenu editProfileMENU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton userBackBTN;
    private javax.swing.JMenuBar userMENU;
    // End of variables declaration//GEN-END:variables
}
